// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwygydgycdhukyratlov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eWd5ZGd5Y2RodWt5cmF0bG92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Njc2MTYsImV4cCI6MjA2NDA0MzYxNn0.4f3obeCxsN95IcyY6Wvj__5RjJoKFzC5TD3KlOTQnqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);